# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи перестановки та символ Леві-Чивіти.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [8]:
from itertools import *
import numpy as np
import itertools
def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def int_cheak(text):
    val=input(text)
    while type(val) !=int:
        try:
            val = int(val)
        except:
            val=input()
    return int(val)

x=int_cheak("enter the size of your matrix:")
t = list(itertools.permutations('123', x))
matrix=random_matrix(x)
print(matrix)
n=1
leb = len(matrix)


for i in range(1, leb + 1):
    n *= i   #N
v = []
for m in range(leb):
    v.append(m)
    m += 1  #
f=[]
for q in permutations(v):
   bb=(q)
   bb=list(bb)
   f.append(bb) #permutations


for i in range(1,x+1):
    n*=i
pp=0
for i in range(0,x-1):
    qq=1
    gg=from itertools import *
import numpy as np
import itertools
def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def int_cheak(text):
    val=input(text)
    while type(val) !=int:
        try:
            val = int(val)
        except:
            val=input()
    return int(val)

x=int_cheak("enter the size of your matrix:")
t = list(itertools.permutations('123', x))
matrix=random_matrix(x)
print(matrix)
n=1
leb = len(matrix)


for i in range(1, leb + 1):
    n *= i   #N
v = []
for m in range(leb):
    v.append(m)
    m += 1  #
f=[]
for q in permutations(v):
   bb=(q)
   bb=list(bb)
   f.append(bb) #permutations


for i in range(1,x+1):
    n*=i
pp=0
for i in range(0,x-1):
    qq=1
    gg=0
    hh=0
    for o in range (0, x):
        gg=f[i],[o]
        gg=gg[-1]
        p=v[o]
        hh=matrix[p,gg]
        qq*=hh
    print(qq)
    pp+=qq
print('sum',pp)

dete= np.linalg.det(matrix)
print("np.linalg.det: ",dete)0
    hh=0
    for o in range (0, x):
        gg=f[i],[o]
        gg=gg[-1]
        p=v[o]
        hh=matrix[p,gg]
        qq*=hh
    print(qq)
    pp+=qq
print('sum',pp)

dete= np.linalg.det(matrix)
print("np.linalg.det: ",dete)

[[2 7 7]
 [8 4 5]
 [0 5 1]]
range(0, 3)
